AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sanity check environment'
Resources:
  SanityCheck:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ServiceRole: arn:aws:iam::${env:ACCOUNT_ID}:role/BatchRole
      ComputeEnvironmentName: SanityCheck
      ComputeResources:
        MaxvCpus: 1
        SecurityGroupIds:
          - ${env:SECURITY_GROUP_ID}
        Type: SPOT
        Subnets:
          - ${env:SUBNET_ID}
        MinvCpus: 0
        InstanceRole: ecsInstanceRole
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        InstanceTypes:
          - optimal
        DesiredvCpus: 1
      State: ENABLED
  SanityCheckQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref SanityCheckEnv
      JobQueueName: SanityCheckQueue
      Priority: 1
      State: ENABLED
