version: '3.1'
services:
  wca-test-db:
    image: "mysql:8.0.26"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: wca_development
    ports:
      - "8306:3306"
    volumes:
      - ${PWD}/src/main/resources/db/migration:/docker-entrypoint-initdb.d/:ro
