spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:8306/wca_development?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password:
  mail:
    password: password
    username: username
    host: 127.0.0.1
    port: 3025
    protocol: smtp
    test-connection: false

service:
  mail:
    send: true
    to: email@wca.com
    from: email@wca.com
    subject: Test
    logfilepath: log/db-sanity-check.log
