spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:8306/wca_development?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password:
  mail:
    host: smtp.gmail.com
    username: '@mail.username@'
    password: '@mail.password@'
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

service:
  mail:
    send: false
    to: example@email.com
    from: example@email.com
    subject: Test
    logfilepath: log/db-sanity-check.log
